name: VitalMail
version: @version@
main: com.tamrielnetwork.vitalhome.VitalMail
api-version: 1.17
authors: [ Tamriel Network ]
website: https://tamriel.site
description: Gives players the ability to set homes and teleport to them.
commands:
  mail:
    description: "Main command"
    usage: "/home"
permissions:
  vitalhome.home:
    description: "Permission to teleport home"
    default: op
  vitalhome.sethome:
    description: "Permission to set a home"
    default: op
  vitalhome.homes:
    description: "Permission with number of homes a player can set (fex. vitalhome.homes.2 = 2 homes)"
    default: op
  vitalhome.list:
    description: "Permission to list homes"
    default: op
  vitalhome.delay.bypass:
    description: "Permission to bypass delay"
    default: op