name: VitalMail
version: @version@
main: com.tamrielnetwork.vitalmail.VitalMail
api-version: 1.17
authors: [ Tamriel Network ]
website: https://tamriel.site
description: Gives players the ability to set homes and teleport to them.
commands:
  vitalmail:
    description: "Main command"
    usage: "/vitalmail"
permissions:
  vitalmail.read:
    description: "Permission to read mail"
    default: op
  vitalmail.send:
    description: "Permission to send mail"
    default: op
  vitalmail.mails:
    description: "Permission with number of mails a player can send (fex. vitalmail.mails.2 = 2 mails)"
    default: op